export default {
  P0: {
    template: "",
    label: "Input (default)",
    description: 'create your own template in the form "... [X] ... [Y] ..."; e.g., "[X] was born in [Y]."',
    type: "",
    manualParaphrase: [],
  },
  P19: {
    template: "[X] was born in [Y] .",
    label: "place of birth",
    description:
      "most specific known (e.g. city instead of country, or hospital instead of city) birth location of a person, animal or fictional character",
    type: "N-1",
    manualParaphrase: [
      "[X] was born in [Y] .",
      "[X] was born in [Y].",
      "[X] is born in [Y].",
      "[X] was born in [Y]",
      "[X] was born [Y].",
      "[X] was born at [Y].",
      "[X] comes from [Y].",
      "[X] was created in [Y].",
      "[X] has been born in [Y].",
      "[X] is from [Y].",
      "[X] was born on [Y].",
      "[X] originated in [Y].",
      "[X] born in [Y].",
      "[X] originates from [Y].",
      "[X] was taken from [Y].",
      "[X] stems from [Y].",
      "[X] arose in [Y].",
      "[X] is taken from [Y].",
      "[X] came from [Y].",
      "[X] was written in [Y].",
      "[X] was made in [Y].",
      "[X] was [Y] born.",
      "[X] [Y] was born.",
      "[X] is in [Y].",
      "[X] is born in [Y]",
      "[X] is born [Y].",
      "[X] was born [Y]",
      "[X] had been born in [Y].",
      "[X] was born. [Y]",
      "[X] was born into [Y].",
    ],
  },
  P20: {
    template: "[X] died in [Y] .",
    label: "place of death",
    description:
      "most specific known (e.g. city instead of country, or hospital instead of city) death location of a person, animal or fictional character",
    type: "N-1",
    manualParaphrase: [
      "[X] died in [Y] .",
      "[X] died in [Y].",
      "[X] died [Y].",
      "[X] died in the year [Y].",
      "[X] died in the [Y].",
      "[X] died at [Y].",
      "[X] died the year [Y].",
      "[X] has died in [Y].",
      "[X] died in year [Y].",
      "[X] passed away in [Y].",
      "[X] died in [Y]",
      "[X] died on [Y].",
      "[X] died in [Y] year.",
      "[X] died at the [Y].",
      "[X] died inside [Y].",
      "[X] [Y] died.",
      "[X] died that year [Y].",
      "[X] died in the year [Y]",
      "[X] died [Y]",
      "[X] died. [Y]",
    ],
  },
  P279: {
    template: "[X] is a subclass of [Y] .",
    label: "subclass of",
    description:
      "all instances of these items are instances of those items; this item is a class (subset) of that item. Not to be confused with P31 (instance of)",
    type: "N-1",
    manualParaphrase: [
      "[X] is a subclass of [Y] .",
      "[X] is a subclass of [Y].",
      "[X] is the subclass of [Y].",
      "[X] is a sub class of [Y].",
      "[X] is a subset of [Y].",
      "[X] is a subclass of [Y]",
      "[X] is a subclass to [Y].",
      "[X] is a subgroup of [Y].",
      "[X] is a sublayer of [Y].",
      "[X] is a subclass of the [Y].",
      "[X] is a sub-class of [Y].",
      "[X] is a substrate of [Y].",
      "[X] is the underclass of [Y].",
      "[X] is the sub class of [Y].",
      "[X] is a sub-group of [Y].",
      "[X] is subclass of [Y].",
      "[X] is a base layer of [Y].",
      "[X] is a lower layer of [Y].",
      "[X] is the subclass [Y].",
      "[X] is an underlayer of [Y].",
      "[X] is a layer of [Y].",
      "[X] is a sub group of [Y].",
      "[X] is subset of [Y].",
      "[X] is an underclass of [Y].",
      "[X] is a subclass [Y].",
      "[X] is the sub-class of [Y]",
      "[X] is a substrate of [Y]",
      "[X] is a subclass of the [Y]",
      "[X] is a sub-set of [Y]",
    ],
  },
  P37: {
    template: "The official language of [X] is [Y] .",
    label: "official language",
    description: "language designated as official by this item",
    type: "N-1",
    manualParaphrase: [
      "The official language of [X] is [Y] .",
      "The official language of [X] is [Y].",
      "The official language for [X] is [Y].",
      "[X] is the official language of [Y].",
      "The official [X] language is [Y].",
      "The official language of [X] is [Y]",
      "The official language [X] is [Y].",
      "The official national language of [X] is [Y].",
      "The official local language of [X] is [Y].",
      "The official official language of [X] is [Y].",
      "Official language of [X] is [Y].",
      "The official language is [X] [Y].",
      "The official language for [X] is [Y]",
      "[X] is [Y].",
      "[X] is officially [Y].",
    ],
  },
  P413: {
    template: "[X] plays in [Y] position .",
    label: "position played on team / speciality",
    description: "position or specialism of a player on a team, e.g. Small Forward",
    type: "N-1",
    manualParaphrase: [
      "[X] plays in [Y] position .",
      "[X] plays in [Y] position.",
      "[X] plays in position [Y].",
      "[X] plays in [Y] -position.",
      "[X] plays in the [Y] position.",
      "[X] plays in the [Y] -position.",
      "[X] plays at [Y] position.",
      "[X] plays on [Y] position.",
      "[X] is playing in [Y] position.",
      "[X] plays in the position [Y].",
      "[X] plays in [Y] -Position.",
      "[X] is playing in position [Y].",
      "[X] plays to [Y] position.",
      "[X] is in [Y] position.",
      "[X] plays on [Y] -position.",
      "[X] is in position [Y].",
      "[X] plays at [Y] -position.",
      "[X] is playing in the [Y] position.",
      "[X] is in the [Y] position.",
      "[X] plays the position [Y].",
      "[X] plays at position [Y].",
      "[X] plays [Y] position.",
      "[X] is in [Y] -position.",
      "[X] plays in [Y] position",
      "[X] play in [Y] position.",
      "[X] plays in [Y].",
      "[X] plays the [Y] position.",
      "[X] is playing in [Y] -position",
      "[X] is playing in the [Y] position",
    ],
  },
  P449: {
    template: "[X] was originally aired on [Y] .",
    label: "original network",
    description: "network(s) the radio or television show was originally aired on,  including",
    type: "N-1",
    manualParaphrase: [
      "[X] was originally aired on [Y] .",
      "[X] was originally broadcast on [Y].",
      "[X] was originally aired on [Y].",
      "[X] originally aired on [Y].",
      "[X] was originally broadcast in [Y].",
      "[X] was originally aired in [Y].",
      "[X] was originally shown on [Y].",
      "[X] was originally broadcast via [Y].",
      "[X] originally aired in [Y].",
      "[X] was originally shown in [Y].",
      "[X] was originally sent to [Y].",
      "[X] was originally transmitted on [Y].",
      "[X] was originally broadcast on [Y]",
      "[X] was originally broadcast by [Y].",
      "[X] was originally on [Y].",
      "[X] was originally sent on [Y].",
      "[X] was originally transmitted in [Y].",
      "[X] was originally broadcast over [Y].",
      "[X] was originally sent in [Y].",
      "[X] was originally broadcast at [Y].",
      "[X] was originally aired by [Y].",
      "[X] originally aired on [Y]",
      "[X] was originally broadcast on the [Y].",
      "[X] was originally broadcasted on [Y]",
      "[X] was originally broadcasted in [Y]",
    ],
  },
  P47: {
    template: "[X] shares border with [Y] .",
    label: "shares border with",
    description:
      "countries or administrative subdivisions, of equal level, that this item borders, either by land or water",
    type: "N-M",
    manualParaphrase: [
      "[X] shares border with [Y] .",
      "[X] borders on [Y].",
      "[X] borders [Y].",
      "[X] shares a border with [Y].",
      "[X] has a common border with [Y].",
      "[X] adjoins [Y].",
      "[X] shares a boundary with [Y].",
      "[X] verges on [Y].",
      "[X] is bordering on [Y].",
      "[X] shares the border with [Y].",
      "[X] borders with [Y].",
      "[X] has a shared border with [Y].",
      "[X] has a border with [Y].",
      "[X] shares the boundary with [Y].",
      "[X] has the same border as [Y].",
      "[X] has the common border with [Y].",
      "[X] has common boundaries with [Y].",
      "[X] divides the border with [Y].",
      "[X] has common borders with [Y].",
      "[X] has common limits with [Y].",
      "[X] shares common boundaries with [Y].",
      "[X] shares borders with [Y].",
      "[X] has common limitations with [Y].",
      "[X] communicates the border with [Y].",
      "[X] will share the border with [Y].",
      "[X] has a common boundary with [Y]",
      "[X] is bordering on [Y]",
      "[X] shares a border with [Y]",
      "[X] has the same boundary as [Y]",
      "[X] has a common border with [Y]",
    ],
  },
  P138: {
    template: "[X] is named after [Y] .",
    label: "named after",
    description: "entity or event that inspired the subject's name, or namesake (in at least one language)",
    type: "N-1",
    manualParaphrase: [
      "[X] is named after [Y] .",
      "[X] is named after [Y].",
      "[X] is named for [Y].",
      "[X] is named after [Y]",
      "[X] is called after [Y].",
      "[X] was named after [Y].",
      "[X] is after [Y].",
      "[X] is named [Y].",
      "[X] is called [Y].",
      "[X] has the name [Y].",
      "[X] has been named after [Y].",
      "[X] means after [Y].",
      "[X] bears the name [Y].",
      "[X] was named for [Y].",
      "[X] carries the name [Y].",
      "[X] is called for [Y].",
      "[X] is named by [Y].",
      "[X] is the name [Y].",
      "[X] is named to [Y].",
      "[X] will be named after [Y]",
      "[X] means [Y].",
      "[X] after [Y].",
      "[X] is given after [Y].",
      "[X] is given the name [Y]",
      "[X] is called after [Y]",
    ],
  },
  P364: {
    template: "The original language of [X] is [Y] .",
    label: "original language of film or TV show",
    description:
      'language in which a film or a performance work was originally created. Deprecated for written works; use P407 ("language of work or name") instead.',
    type: "N-1",
    manualParaphrase: [
      "The original language of [X] is [Y] .",
      "The original language of [X] is [Y].",
      "The original language for [X] is [Y].",
      "The native language of [X] is [Y].",
      "The source language of [X] is [Y].",
      "[X] is the original language of [Y].",
      "The primary language of [X] is [Y].",
      "The original [X] language is [Y].",
      "The original language of [X] is [Y]",
      "The original language of [X] was [Y].",
      "[X] is the original [Y].",
      "The initial language of [X] is [Y].",
      "The source language for [X] is [Y].",
      "The language of [X] is [Y].",
      "[X] is original [Y].",
      "[X] is in original [Y].",
      "The default language of [X] is [Y].",
      "The source of [X] is [Y].",
      "[X] is the source language of [Y].",
      "[X] is [Y].",
      "[X] is originally [Y].",
      "The original language of [X] is [Y]..",
      "[X] is in [Y].",
      "[X] is the original [Y]",
      "The original language for [X] is [Y]..",
    ],
  },
  P463: {
    template: "[X] is a member of [Y] .",
    label: "member of",
    description:
      "organization or club to which the subject belongs. Do not use for membership in ethnic or social groups, nor for holding a position such as a member of parliament (use P39 for that).",
    type: "N-M",
    manualParaphrase: [
      "[X] is a member of [Y] .",
      "[X] is a member of [Y].",
      "[X] is member of [Y].",
      "[X] belongs to [Y].",
      "[X] is a member of [Y]",
      "[X] is the member of [Y].",
      "[X] is a Member of [Y].",
      "[X] is a [Y] member.",
      "[X] is part of [Y].",
      "[X] is member of the [Y].",
      "[X] is member of [Y]",
      "[X] is a member in [Y].",
      "[X] is a user of [Y].",
      "[X] is member in [Y].",
      "[X] is a member of the [Y]",
      "[X] is a [Y].",
      "[X] belongs to [Y]",
      "[X] is one of [Y].",
      "[X] is a member [Y].",
      "[X] is an [Y] member.",
      "[X] belong to [Y].",
      "[X] joined [Y].",
      "[X] is [Y].",
    ],
  },
  P101: {
    template: "[X] works in the field of [Y] .",
    label: "field of work",
    description: "specialization of a person or organization; see P106 for the occupation",
    type: "N-M",
    manualParaphrase: [
      "[X] works in the field of [Y] .",
      "[X] works in the range [Y].",
      "[X] works in the range of [Y].",
      "[X] works in range [Y].",
      "[X] works in the area [Y].",
      "[X] works in area [Y].",
      "[X] works in [Y].",
      "[X] works in the [Y] area.",
      "[X] operates in the range of [Y].",
      "[X] works in the [Y] range.",
      "[X] works within the range of [Y].",
      "[X] is in the range of [Y].",
      "[X] works in the field [Y].",
      "[X] works in the area of [Y].",
      "[X] works in the field of [Y].",
      "[X] works in section [Y].",
      "[X] works in the [Y] domain.",
      "[X] works in the [Y] field.",
      "[X] works in the range of [Y]",
      "[X] works on [Y].",
      "[X] works in the field of [Y]",
      "[X] works in the area of [Y]",
      "[X] is working in the field of [Y]",
      "[X] works in the domain of [Y]",
      "[X] works on the field of [Y]",
      "[X] works on [Y]",
      "[X] works in [Y]",
    ],
  },
  P106: {
    template: "[X] is a [Y] by profession .",
    label: "occupation",
    description: 'occupation of a person; see also "field of work" (Property:P101), "position held" (Property:P39)',
    type: "N-M",
    manualParaphrase: [
      "[X] is a [Y] by profession .",
      "[X] is a [Y] by profession.",
      "[X] is [Y] by profession.",
      "[X] is by profession [Y].",
      "[X] is a [Y] by trade.",
      "[X] is a [Y].",
      "[X] is a [Y] profession.",
      "[X] is a [Y] by occupation.",
      "[X] is an [Y] by profession.",
      "[X] is a profession [Y].",
      "[X] is [Y].",
      "[X] is a [Y] occupation.",
      "[X] is by trade [Y].",
      "[X] is [Y] by trade.",
      "[X] is profession [Y].",
      "[X] is an occupation [Y].",
      "[X] is by profession a [Y]",
      "[X] is a professional [Y].",
      "[X] is professionally [Y].",
      "[X] is professional [Y].",
      "[X] is by profession [Y]",
      "[X] is a [Y] by profession",
      "[X] is a [Y]",
      "[X] is professionally a [Y]",
      "[X] is a by profession [Y]",
      "[X] is [Y] by profession",
      "[X] is an [Y]",
    ],
  },
  P527: {
    template: "[X] consists of [Y] .",
    label: "has part",
    description:
      'part of this subject; inverse property of "part of" (P361). See also "has parts of the class" (P2670).',
    type: "N-M",
    manualParaphrase: [
      "[X] consists of [Y] .",
      "[X] consists of [Y].",
      "[X] is [Y].",
      "[X] is made of [Y].",
      "[X] contains [Y].",
      "[X] consist of [Y].",
      "[X] consists of [Y]",
      "[X] consisting of [Y].",
      "[X] includes [Y].",
      "[X] is made of [Y]",
      "[X] composed of [Y].",
      "[X] consists of [Y]..",
      "[X] consists of [Y]:",
      "[X] spans [Y].",
      "[X] comprises [Y].",
      "[X] consisting of [Y]",
      "[X] covers [Y].",
      "[X] is [Y]..",
      "[X] contains [Y]",
      "[X] has [Y].",
      "[X] is [Y]:",
      "[X] is made of [Y]..",
      "[X] contain [Y].",
      "[X] is [Y]",
      "[X] is made of [Y]:",
      "[X] contains [Y]:",
      "[X] consist of [Y]:",
      "[X] contains [Y]..",
      "[X] means [Y].",
      "[X] = [Y].",
    ],
  },
  P530: {
    template: "[X] maintains diplomatic relations with [Y] .",
    label: "diplomatic relation",
    description: "diplomatic relations of the country",
    type: "N-M",
    manualParaphrase: [
      "[X] maintains diplomatic relations with [Y] .",
      "[X] maintains diplomatic relations with [Y].",
      "[X] has diplomatic relations with [Y].",
      "[X] maintains diplomatic relations to [Y].",
      "[X] maintains diplomatic ties with [Y].",
      "[X] maintains diplomatic relationships with [Y].",
      "[X] has diplomatic relations to [Y].",
      "[X] maintains diplomatic relations with [Y]",
      "[X] maintain diplomatic relations with [Y].",
      "[X] maintains diplomatic contacts with [Y].",
      "[X] have diplomatic relations with [Y].",
      "[X] is in diplomatic relations with [Y].",
      "[X] holds diplomatic relations with [Y].",
      "[X] have diplomatic relations to [Y].",
      "[X] maintain diplomatic relations to [Y].",
      "[X] maintain diplomatic ties with [Y].",
      "[X] maintains a diplomatic relationship with [Y]",
    ],
  },
  P176: {
    template: "[X] is produced by [Y] .",
    label: "manufacturer",
    description: "manufacturer or producer of this product",
    type: "N-1",
    manualParaphrase: [
      "[X] is produced by [Y] .",
      "[X] is produced by [Y].",
      "[X] is created by [Y].",
      "[X] is generated by [Y].",
      "[X] is made by [Y].",
      "[X] is produced by [Y]",
      "[X] will be created by [Y].",
      "[X] comes from [Y].",
      "[X] is from [Y].",
      "[X] is created from [Y].",
      "[X] was produced by [Y].",
      "[X] is manufactured by [Y].",
      "[X] is created with [Y].",
      "[X] will be produced by [Y].",
      "[X] is produced from [Y].",
      "[X] is generated from [Y].",
      "[X] is created by [Y]",
      "[X] produced by [Y].",
      "[X] is done by [Y].",
      "[X] is generated with [Y].",
      "[X] originates from [Y].",
      "[X] is by [Y].",
      "[X] came from [Y].",
      "[X] is being produced by [Y]",
      "[X] originated from [Y].",
      "[X] was taken from [Y].",
      "[X] will be produced by [Y]",
    ],
  },
  P27: {
    template: "[X] is [Y] citizen .",
    label: "country of citizenship",
    description: "the object is a country that recognizes the subject as its citizen",
    type: "N-M",
    manualParaphrase: [
      "[X] is [Y] citizen .",
      "[X] is a [Y] citizen.",
      "[X] is a citizen of [Y].",
      "[X] is [Y] -citizen.",
      "[X] is [Y] citizen.",
      "[X] is citizen [Y].",
      "[X] is a [Y] -citizen.",
      "[X] is citizen of [Y].",
      "[X] is a citizen [Y].",
      "[X] is [Y] a citizen.",
      "[X] is [Y] -Citizen.",
      "[X] is [Y] Citizen.",
      "[X] is Citizen of [Y].",
      "[X] is a [Y] national.",
      "[X] is [Y] a national.",
      "[X] is a citizen of [Y]",
      "[X] is citizens of [Y].",
      "[X] is a national [Y].",
      "[X] is citizen of [Y]",
      "[X] is citizens [Y].",
      "[X] is a citizen [Y]",
      "[X] is [Y].",
      "[X] is citizen [Y]",
      "[X] is a citizen. [Y]",
      "[X] is [Y] a citizen",
    ],
  },
  P407: {
    template: "[X] was written in [Y] .",
    label: "language of work or name",
    description:
      "language associated with this creative work (such as books, shows, songs, or websites) or a name (for persons use P103 and P1412)",
    type: "N-1",
    manualParaphrase: [
      "[X] was written in [Y] .",
      "[X] was written in [Y].",
      "[X] is written in [Y].",
      "[X] was in [Y].",
      "[X] was written in [Y]",
      "[X] is in [Y].",
      "[X] comes from [Y].",
      "[X] is written in [Y]",
      "[X] is from [Y].",
      "[X] was written into [Y].",
      "[X] was in [Y] written.",
      "[X] originates from [Y].",
      "[X] was composed in [Y].",
      "[X] was taken from [Y].",
      "[X] stems from [Y].",
      "[X] was created in [Y].",
      "[X] is taken from [Y].",
      "[X] came from [Y].",
      "[X] is written into [Y].",
      "[X] was set in [Y].",
      "[X] has been written in [Y]",
      "[X] is in [Y]",
      "[X] written in [Y].",
      "[X] was written in [Y],",
      "[X] was composed in [Y]",
      "[X] was written in [Y];",
    ],
  },
  P30: {
    template: "[X] is located in [Y] .",
    label: "continent",
    description: "continent of which the subject is a part",
    type: "N-1",
    manualParaphrase: [
      "[X] is located in [Y] .",
      "[X] is in [Y].",
      "[X] is located in [Y].",
      "[X] is found in [Y].",
      "[X] lies in [Y].",
      "[X] is in the [Y].",
      "[X] is placed in [Y].",
      "[X] is inside [Y].",
      "[X] is located in the [Y].",
      "[X] is [Y].",
      "[X] is in [Y]",
      "[X] is located in [Y]",
      "[X] is located at [Y].",
      "[X] is on [Y].",
      "[X] stands in [Y].",
      "[X] is written in [Y].",
      "[X] is set to [Y].",
      "[X] will be in [Y].",
      "[X] is in [Y]..",
      "[X] is located in the [Y]",
      "[X] is located in [Y]..",
      "[X] in [Y].",
      "[X] is found in [Y]..",
      "[X] located in [Y]..",
      "[X] is in [Y];",
      "[X] is in [Y],",
    ],
  },
  P178: {
    template: "[X] is developed by [Y] .",
    label: "developer",
    description: "organisation or person that developed the item",
    type: "N-M",
    manualParaphrase: [
      "[X] is developed by [Y] .",
      "[X] is developed by [Y].",
      "[X] was developed by [Y].",
      "[X] is a development of [Y].",
      "[X] is developed by [Y]",
      "[X] is created by [Y].",
      "[X] developed by [Y].",
      "[X] is an evolution of [Y].",
      "[X] is designed by [Y].",
      "[X] was created by [Y].",
      "[X] was designed by [Y].",
      "[X] was developed by [Y]",
      "[X] is developed from [Y].",
      "[X] is the development of [Y].",
      "[X] has been developed by [Y]",
      "[X] is a [Y] development.",
      "[X] is developed through [Y].",
      "[X] is an evolution of [Y]",
      "[X] is being developed by [Y]",
      "[X] is the evolution of [Y]",
    ],
  },
  P1376: {
    template: "[X] is the capital of [Y] .",
    label: "capital of",
    description:
      "country, state, department, canton or other administrative division of which the municipality is the governmental seat",
    type: "1-1",
    manualParaphrase: [
      "[X] is the capital of [Y] .",
      "[X] is the capital of [Y].",
      "[X] is the capital city of [Y].",
      "[X] is the capital [Y].",
      "[X] is the capital of the [Y].",
      "[X] is the capital city [Y].",
      "[X] is the Capital of [Y].",
      "[X] is the capital of [Y]",
      "[X] is capital of [Y].",
      "[X] is capital [Y].",
      "[X] is the main town of [Y].",
      "[X] is the main place of [Y].",
      "[X] is the [Y] capital.",
      "[X] is the capital city of the [Y].",
      "[X] is [Y] 's capital.",
      "[X] is the main village of [Y].",
      "[X] is the capital city of [Y]",
      "[X] is Capital [Y].",
      "[X] is [Y] capital.",
      "[X] is the main city of [Y].",
      "[X] is the [Y] capital city.",
      "[X] is the [Y] 's capital.",
      "[X] is the capital town of [Y].",
      "[X] is the Capital [Y].",
      "[X] is the capital [Y]",
      "[X] means capital [Y].",
      "[X] is the capital city [Y]",
      "[X] means Capital [Y].",
      "[X] is capital. [Y]",
    ],
  },
  P131: {
    template: "[X] is located in [Y] .",
    label: "located in the administrative territorial entity",
    description:
      "the item is located on the territory of the following administrative entity. Use P276 (location) for specifying the location of non-administrative places and for items about events",
    type: "N-1",
    manualParaphrase: [
      "[X] is located in [Y] .",
      "[X] is in [Y].",
      "[X] is located in [Y].",
      "[X] is found in [Y].",
      "[X] lies in [Y].",
      "[X] is in the [Y].",
      "[X] is placed in [Y].",
      "[X] is inside [Y].",
      "[X] is located in the [Y].",
      "[X] is [Y].",
      "[X] is in [Y]",
      "[X] is located in [Y]",
      "[X] is located at [Y].",
      "[X] is on [Y].",
      "[X] stands in [Y].",
      "[X] is written in [Y].",
      "[X] is set to [Y].",
      "[X] will be in [Y].",
      "[X] is in [Y]..",
      "[X] is located in the [Y]",
      "[X] is located in [Y]..",
      "[X] in [Y].",
      "[X] is found in [Y]..",
      "[X] located in [Y]..",
      "[X] is in [Y];",
      "[X] is in [Y],",
    ],
  },
  P1412: {
    template: "[X] used to communicate in [Y] .",
    label: "languages spoken, written or signed",
    description: "language(s) that a person speaks or writes, including the native language(s)",
    type: "N-M",
    manualParaphrase: [
      "[X] used to communicate in [Y] .",
      "[X] used to communicate in [Y].",
      "[X] communicated in [Y].",
      "[X] to communicate in [Y].",
      "[X] is used to communicate in [Y].",
      "[X] communicates in [Y].",
      "[X] used [Y] to communicate.",
      "[X] previously communicated in [Y].",
      "[X] for communicating in [Y].",
      "[X] formerly communicated in [Y].",
      "[X] communicated earlier in [Y].",
      "[X] used to communicate with [Y].",
      "[X] to communicate with [Y].",
      "[X] used to communicate in [Y]",
      "[X] communicated with [Y].",
      "[X] is used to communicate in [Y]",
      "[X] communicates with [Y].",
      "[X] uses [Y] to communicate.",
      "[X] was using [Y] to communicate.",
      "[X] used [Y] for communication.",
      "[X] communicated in [Y]",
      "[X] communicate in [Y].",
      "[X] communicated within [Y].",
      "[X] was used to communicate in [Y]",
      "[X] used [Y] for communicating.",
      "[X] communicates in [Y]",
      "[X] use [Y] to communicate.",
      "[X] are used to communicate in [Y].",
      "[X] in order to communicate in [Y]",
      "[X] used to communicate within [Y].",
    ],
  },
  P108: {
    template: "[X] works for [Y] .",
    label: "employer",
    description: "person or organization for which the subject works or worked",
    type: "N-M",
    manualParaphrase: [
      "[X] works for [Y] .",
      "[X] works for [Y].",
      "[X] works with [Y].",
      "[X] works on [Y].",
      "[X] is working for [Y].",
      "[X] will work for [Y].",
      "[X] Works for [Y].",
      "[X] is suitable for [Y].",
      "[X] works for [Y]",
      "[X] functions for [Y].",
      "[X] works after [Y].",
      "[X] works according to [Y].",
      "[X] works in [Y].",
      "[X] is for [Y].",
      "[X] uses [Y].",
      "[X] works at [Y].",
      "[X] will work with [Y].",
      "[X] works to [Y].",
      "[X] works with [Y]",
      "[X] functions with [Y].",
      "[X] Works with [Y].",
      "[X] works by [Y].",
      "[X] operates with [Y].",
      "[X] is appropriate for [Y].",
      "[X] will work on [Y].",
      "[X] works using [Y].",
      "[X] is using [Y].",
      "[X] is suitable for [Y]",
      "[X] is for [Y]",
      "[X] is working with [Y]",
    ],
  },
  P136: {
    template: "[X] plays [Y] music .",
    label: "genre",
    description:
      "creative work's genre or an artist's field of work (P101). Use main subject (P921) to relate creative works to their topic",
    type: "N-1",
    manualParaphrase: [
      "[X] plays [Y] music .",
      "[X] plays [Y] music.",
      "[X] plays [Y] -music.",
      "[X] is playing [Y] music.",
      "[X] plays music [Y].",
      "[X] plays [Y] Music.",
      "[X] plays music by [Y].",
      "[X] plays [Y] -Music.",
      "[X] plays music on [Y].",
      "[X] play [Y] music.",
      "[X] plays [Y] music",
      "[X] plays music from [Y].",
      "[X] plays [Y].",
      "[X] is playing music [Y].",
      "[X] performs [Y] music.",
      "[X] is playing [Y].",
      "[X] plays the music [Y].",
      "[X] plays Music [Y].",
      "[X] play music [Y].",
      "[X] playing music [Y].",
      "[X] plays music [Y]",
      "[X] performs [Y].",
      "[X] is playing [Y] -music",
      "[X] playing [Y] music.",
      "[X] is [Y].",
      "[X] play [Y].",
      "[X] playing [Y].",
      "[X] plays [Y]",
    ],
  },
  P17: {
    template: "[X] is located in [Y] .",
    label: "country",
    description: "sovereign state of this item; don't use on humans",
    type: "N-1",
    manualParaphrase: [
      "[X] is located in [Y] .",
      "[X] is in [Y].",
      "[X] is located in [Y].",
      "[X] is found in [Y].",
      "[X] lies in [Y].",
      "[X] is in the [Y].",
      "[X] is placed in [Y].",
      "[X] is inside [Y].",
      "[X] is located in the [Y].",
      "[X] is [Y].",
      "[X] is in [Y]",
      "[X] is located in [Y]",
      "[X] is located at [Y].",
      "[X] is on [Y].",
      "[X] stands in [Y].",
      "[X] is written in [Y].",
      "[X] is set to [Y].",
      "[X] will be in [Y].",
      "[X] is in [Y]..",
      "[X] is located in the [Y]",
      "[X] is located in [Y]..",
      "[X] in [Y].",
      "[X] is found in [Y]..",
      "[X] located in [Y]..",
      "[X] is in [Y];",
      "[X] is in [Y],",
    ],
  },
  P39: {
    template: "[X] has the position of [Y] .",
    label: "position held",
    description: "subject currently or formerly holds the object position or public office",
    type: "N-M",
    manualParaphrase: [
      "[X] has the position of [Y] .",
      "[X] has the position of [Y].",
      "[X] is the position of [Y].",
      "[X] takes the position of [Y].",
      "[X] is in position [Y].",
      "[X] is in the position of [Y].",
      "[X] has the position [Y].",
      "[X] has the location of [Y].",
      "[X] has the status of [Y].",
      "[X] is the location of [Y].",
      "[X] is in position of [Y].",
      "[X] has position [Y].",
      "[X] is positioned [Y].",
      "[X] is at position [Y].",
      "[X] has the position of the [Y].",
      "[X] is positioned in [Y].",
      "[X] is set to [Y].",
      "[X] occupies the position of [Y].",
      "[X] has the position of a [Y].",
      "[X] takes the place of [Y].",
      "[X] has the [Y] position.",
      "[X] has the state of [Y].",
      "[X] is the status of [Y].",
      "[X] is equal to [Y].",
      "[X] takes the position of [Y]",
      "[X] is the [Y] position.",
      "[X] is [Y].",
      "[X] replaces [Y].",
      "[X] is in [Y].",
      "[X] has the status [Y].",
    ],
  },
  P264: {
    template: "[X] is represented by music label [Y] .",
    label: "record label",
    description: "brand and trademark associated with the marketing of subject music recordings and music videos",
    type: "N-1",
    manualParaphrase: [
      "[X] is represented by music label [Y] .",
      "[X] is represented by the music label [Y].",
      "[X] is represented by the record label [Y].",
      "[X] is represented by the [Y] music label.",
      "[X] is represented by the label [Y].",
      "[X] is represented by [Y].",
      "[X] is represented by music label [Y].",
      "[X] is represented by the [Y] label.",
      "[X] is represented by the [Y] record label.",
      "[X] is represented by the music label [Y]",
      "[X] is represented by the record label [Y]",
      "[X] represented by the music label [Y]",
      "[X] is represented by the [Y] music label",
      "[X] is represented by the label [Y]",
      "[X] is represented by music label [Y]",
      "[X] is represented by [Y]",
    ],
  },
  P276: {
    template: "[X] is located in [Y] .",
    label: "location",
    description:
      "location of the item, physical object or event is within. In case of an administrative entity use P131. In case of a distinct terrain feature use P706.",
    type: "N-1",
    manualParaphrase: [
      "[X] is located in [Y] .",
      "[X] is in [Y].",
      "[X] is located in [Y].",
      "[X] is found in [Y].",
      "[X] lies in [Y].",
      "[X] is in the [Y].",
      "[X] is placed in [Y].",
      "[X] is inside [Y].",
      "[X] is located in the [Y].",
      "[X] is [Y].",
      "[X] is in [Y]",
      "[X] is located in [Y]",
      "[X] is located at [Y].",
      "[X] is on [Y].",
      "[X] stands in [Y].",
      "[X] is written in [Y].",
      "[X] is set to [Y].",
      "[X] will be in [Y].",
      "[X] is in [Y]..",
      "[X] is located in the [Y]",
      "[X] is located in [Y]..",
      "[X] in [Y].",
      "[X] is found in [Y]..",
      "[X] located in [Y]..",
      "[X] is in [Y];",
      "[X] is in [Y],",
    ],
  },
  P937: {
    template: "[X] used to work in [Y] .",
    label: "work location",
    description: "location where persons were active",
    type: "N-M",
    manualParaphrase: [
      "[X] used to work in [Y] .",
      "[X] used to work in [Y].",
      "[X] worked in [Y].",
      "[X] used to work at [Y].",
      "[X] previously worked in [Y].",
      "[X] used to work on [Y].",
      "[X] formerly worked in [Y].",
      "[X] used to work under [Y].",
      "[X] used to work for [Y].",
      "[X] was working in [Y].",
      "[X] used to work with [Y].",
      "[X] worked in [Y] before.",
      "[X] has worked in [Y].",
      "[X] used to function in [Y].",
      "[X] has worked in [Y] before.",
      "[X] worked on [Y].",
      "[X] used to be in [Y].",
      "[X] works in [Y].",
      "[X] previously worked under [Y].",
      "[X] used to work in [Y]",
      "[X] formerly worked under [Y].",
      "[X] used to be under [Y].",
      "[X] was working on [Y].",
      "[X] was in [Y].",
      "[X] worked at [Y].",
      "[X] used to operate under [Y].",
      "[X] was formerly in [Y].",
      "[X] has worked at [Y].",
      "[X] has been working in [Y]",
    ],
  },
  P140: {
    template: "[X] is affiliated with the [Y] religion .",
    label: "religion",
    description: "religion of a person, organization or religious building, or associated with this subject",
    type: "N-1",
    manualParaphrase: [
      "[X] is affiliated with the [Y] religion .",
      "[X] is related to the [Y] religion.",
      "[X] is associated with the [Y] religion.",
      "[X] is related to [Y] religion.",
      "[X] is related to religion [Y].",
      "[X] is connected to the [Y] religion.",
      "[X] is connected to religion [Y].",
      "[X] is close to the [Y] religion.",
      "[X] is connected with the [Y] religion.",
      "[X] is connected with religion [Y].",
      "[X] is associated with [Y] religion.",
      "[X] is linked to the [Y] religion.",
      "[X] is connected to the religion [Y].",
      "[X] is associated with religion [Y].",
      "[X] is related to the religion [Y].",
      "[X] is linked to religion [Y].",
      "[X] is connected with [Y] religion.",
      "[X] is close to [Y] religion.",
      "[X] is close to the [Y] -religion.",
      "[X] is connected to [Y] religion.",
      "[X] is close to [Y] -religion.",
      "[X] is very close to the [Y] religion.",
      "[X] is related to the [Y] religion",
      "[X] is connected with the [Y] religion",
      "[X] is related to [Y] religion",
      "[X] is connected to the [Y] religion",
      "[X] is related to the [Y] -religion",
      "[X] is associated with the [Y] religion",
      "[X] is related to [Y] -religion",
    ],
  },
  P1303: {
    template: "[X] plays [Y] .",
    label: "instrument",
    description: "musical instrument that a person plays",
    type: "N-M",
    manualParaphrase: [
      "[X] plays [Y] .",
      "[X] plays [Y].",
      "[X] is playing [Y].",
      "[X] performs [Y].",
      "[X] is [Y].",
      "[X] play [Y].",
      "[X] playing [Y].",
      "[X] plays [Y]",
      "[X] [Y].",
      "[X] playing [Y]",
      "[X] Play [Y].",
      "[X] is playing [Y]",
      "[X] play [Y]",
      "[X] [Y] play.",
      "[X] performs [Y]",
      "[X] played [Y]",
    ],
  },
  P127: {
    template: "[X] is owned by [Y] .",
    label: "owned by",
    description: "owner of the subject",
    type: "N-1",
    manualParaphrase: [
      "[X] is owned by [Y] .",
      "[X] belongs to [Y].",
      "[X] is the property of [Y].",
      "[X] is owned by [Y].",
      "[X] is property of [Y].",
      "[X] belongs [Y].",
      "[X] belongs to [Y]",
      "[X] is [Y].",
      "[X] belong to [Y].",
      "[X] is held by [Y].",
      "[X] is part of [Y].",
      "[X] is a property of [Y].",
      "[X] is the property of [Y]",
      "[X] is owned by [Y]",
      "[X] is property of [Y]",
      "[X] is one of [Y].",
      "[X] are property of [Y]",
      "[X] property of [Y]",
    ],
  },
  P103: {
    template: "The native language of [X] is [Y] .",
    label: "native language",
    description: "language or languages a person has learned from early childhood",
    type: "N-1",
    manualParaphrase: [
      "The native language of [X] is [Y] .",
      "The native language of [X] is [Y].",
      "[X] is the native language of [Y].",
      "[X] is [Y].",
      "The native language [X] is [Y].",
      "The native language of [X] is [Y]",
      "[X] is native to [Y].",
      "[X] is [Y] native language.",
      "The native language of the [X] is [Y].",
      "The mother tongue of [X] is [Y].",
      "native language of [X] is [Y].",
      "[X] is the mother language of [Y].",
      "[X] is a native language of [Y].",
      "[X] is the native language of [Y]",
      "[X] native language is [Y].",
      "[X] is [Y] native.",
      "Native language [X] is [Y].",
      "The native [X] language is [Y].",
      "[X] is the mother tongue of [Y]",
      "The native language is [X] [Y].",
      "Native language of [X] is [Y]",
      "[X] is native language [Y].",
      "The native language of the [X] is [Y]",
      "The native language [X] is [Y]",
      "The mother tongue [X] is [Y]",
      "native language of [X] is [Y]",
      "[X] is [Y]",
      "[X] native language is [Y]",
      "[X] means [Y].",
      "[X] = [Y].",
    ],
  },
  P190: {
    template: "[X] and [Y] are twin cities .",
    label: "twinned administrative body",
    description:
      "twin towns, sister cities, twinned municipalities and other localities that have a partnership or cooperative agreement, either legally or informally acknowledged by their governments",
    type: "N-M",
    manualParaphrase: [
      "[X] and [Y] are twin cities .",
      "[X] and [Y] are twin cities.",
      "[X] and [Y] are twin towns.",
      "[X] and [Y] are sister cities.",
      "[X] and [Y] are twinned cities.",
      "[X] and [Y] are town twinning.",
      "[X] and [Y] are twinning.",
      "[X] and [Y] are sister towns.",
      "[X] and [Y] are city twinning.",
      "[X] and [Y] are twinned towns.",
      "[X] and [Y] are twinning cities.",
      "[X] and [Y] are two cities.",
      "[X] and [Y] are twinned.",
      "[X] and [Y] are twin cities",
      "[X] and [Y] are twins.",
      "[X] and [Y] are both twin cities.",
      "[X] and [Y] are two towns.",
      "[X] and [Y] are Twin Cities",
      "[X] and [Y] are twin towns",
      "The [X] and [Y] are twin cities.",
      "The [X] and [Y] are two cities.",
      "[X] and [Y] are both cities.",
      "[X] und [Y] are two cities.",
      "[X] and [Y] are 2 cities.",
      "The [X] and [Y] are twin towns.",
      "[X] and [Y] are twins",
      "[X] and [Y] are two cities",
      "[X] and [Y] are twinned cities",
      "[X] and [Y] are two twin cities",
    ],
  },
  P1001: {
    template: "[X] is a legal term in [Y] .",
    label: "applies to jurisdiction",
    description:
      "the item (an institution, law, public office ...) or statement belongs to or has power over or applies to the value (a territorial jurisdiction: a country, state, municipality, ...)",
    type: "N-M",
    manualParaphrase: [
      "[X] is a legal term in [Y] .",
      "[X] is a legal term in [Y].",
      "[X] is a legal expression in [Y].",
      "[X] is a legal term used in [Y].",
      "[X] is a legal concept in [Y].",
      "[X] is a legal term for [Y].",
      "[X] is a legal term given in [Y].",
      "[X] is the legal term in [Y].",
      "[X] is a legal word in [Y].",
      "[X] is a legal term found in [Y].",
      "[X] is the legal expression in [Y].",
      "[X] is a legal expression of [Y].",
      "[X] is a legal expression for [Y].",
      "[X] is an expression in [Y].",
      "[X] is a legal expression in [Y]",
      "[X] is legal expression in [Y].",
    ],
  },
  P31: {
    template: "[X] is a [Y] .",
    label: "instance of",
    description:
      "that class of which this subject is a particular example and member (subject typically an individual member with a proper name label); different from P279; using this property as a qualifier is deprecated\u2014use P2868 or P3831 instead",
    type: "N-M",
    manualParaphrase: [
      "[X] is a [Y] .",
      "[X] is a [Y].",
      "[X] is an [Y].",
      "[X] is [Y].",
      "[X] is one [Y].",
      "[X] is a [Y]",
      "[X] is the [Y].",
      "[X] is that [Y].",
      "[X] is an [Y]",
      "[X] is this [Y].",
      "[X] is [Y]",
      "[X] means [Y].",
      "[X] is one [Y]",
      "[X] = [Y].",
      "[X] Is a [Y]",
    ],
  },
  P495: {
    template: "[X] was created in [Y] .",
    label: "country of origin",
    description: "country of origin of this item (creative work, food, phrase, product, etc.)",
    type: "N-1",
    manualParaphrase: [
      "[X] was created in [Y] .",
      "[X] was created in [Y].",
      "[X] was founded in [Y].",
      "[X] is created in [Y].",
      "[X] originated in [Y].",
      "[X] was made in [Y].",
      "[X] was established in [Y].",
      "[X] was created in [Y] year.",
      "[X] arose in [Y].",
      "[X] was created in [Y]",
      "[X] was formed in [Y].",
      "[X] was created in year [Y].",
      "[X] was created by [Y].",
      "[X] was written in [Y].",
      "[X] was generated in [Y].",
      "[X] is in [Y].",
      "[X] was added in [Y].",
      "[X] was set up in [Y].",
      "[X] has been created in [Y]",
      "[X] is generated in [Y].",
      "[X] is made in [Y].",
      "[X] was created in the year [Y]",
      "[X] was born in [Y].",
      "[X] was created with [Y].",
      "[X] was founded in [Y]",
      "[X] was established in the year [Y]",
      "[X] came into being in [Y]",
    ],
  },
  P159: {
    template: "The headquarter of [X] is in [Y] .",
    label: "headquarters location",
    description:
      'specific location where an organization\'s headquarters is or has been situated. Inverse property of "occupant" (P466).',
    type: "N-1",
    manualParaphrase: [
      "The headquarter of [X] is in [Y] .",
      "The headquarters of [X] are located in [Y].",
      "The headquarters of [X] is located in [Y].",
      "[X] is headquartered in [Y].",
      "The head office of [X] is in [Y].",
      "The headquarters of [X] is in [Y].",
      "The headquarters of [X] are in [Y].",
      "The headquarter of [X] is in [Y].",
      "[X] has its headquarters in [Y].",
      "[X] headquarters are located in [Y].",
      "[X] is located in [Y].",
      "The head office of [X] is located in [Y]",
      "The headquarters of [X] is located in [Y]",
      "The headquarters of [X] are located in [Y]",
      "The headquarters of [X] is in [Y]",
    ],
  },
  P36: {
    template: "The capital of [X] is [Y] .",
    label: "capital",
    description: "primary city of a country, state or other type of administrative territorial entity",
    type: "1-1",
    manualParaphrase: [
      "The capital of [X] is [Y] .",
      "The capital of [X] is [Y].",
      "The capital city of [X] is [Y].",
      "[X] is the capital of [Y].",
      "The capital [X] is [Y].",
      "The Capital of [X] is [Y].",
      "The capital of the [X] is [Y].",
      "[X] is [Y].",
      "[X] capital is [Y].",
      "[X] 's capital is [Y].",
      "The [X] capital is [Y].",
      "The capital of [X] is [Y]",
      "[X] is [Y] capital.",
      "[X] is the capital city of [Y].",
      "The capital city of [X] is [Y]",
      "The Capital [X] is [Y].",
      "Its capital [X] is [Y].",
      "The capital is [X] [Y].",
      "The capital of the [X] is [Y]",
      "[X] is the Capital of [Y].",
      "[X] is the capital of [Y]",
      "The capital [X] is [Y]",
      "[X] is capital of [Y].",
      "[X] is [Y]",
      "[X] is the capital city of [Y]",
      "[X] means [Y].",
      "[X] = [Y].",
    ],
  },
  P740: {
    template: "[X] was founded in [Y] .",
    label: "location of formation",
    description: "location where a group or organization was formed",
    type: "N-1",
    manualParaphrase: [
      "[X] was founded in [Y] .",
      "[X] was founded in [Y].",
      "[X] was established in [Y].",
      "[X] was formed in [Y].",
      "[X] was created in [Y].",
      "[X] was founded [Y].",
      "[X] was founded in [Y] year.",
      "[X] was set up in [Y].",
      "[X] was founded in the [Y].",
      "[X] was born in [Y].",
      "[X] was founded in [Y]",
      "[X] was founded in the year [Y]",
      "[X] was created in the year [Y].",
      "[X] was founded by [Y].",
      "[X] was formed [Y].",
      "[X] was established [Y].",
      "[X] was founded on [Y].",
      "[X] originated in [Y].",
      "[X] was [Y] founded.",
      "[X] was created [Y].",
      "[X] originated in the year [Y].",
      "[X] was made in the year [Y].",
      "[X] was established in the year [Y]",
      "[X] was written in the year [Y].",
      "[X] was created in year [Y].",
      "[X] arose in [Y].",
      "[X] was formed in the year [Y]",
      "[X] was written in [Y].",
      "[X] was made in [Y].",
      "[X] is in [Y].",
    ],
  },
  P361: {
    template: "[X] is part of [Y] .",
    label: "part of",
    description:
      'object of which the subject is a part (it\'s not useful to link objects which are themselves parts of other objects already listed as parts of the subject). Inverse property of "has part" (P527, see also "has parts of the class" (P2670)).',
    type: "N-1",
    manualParaphrase: [
      "[X] is part of [Y] .",
      "[X] is part of [Y].",
      "[X] belongs to [Y].",
      "[X] is a part of [Y].",
      "[X] is a component of [Y].",
      "[X] is part of the [Y].",
      "[X] is part [Y].",
      "[X] is part of [Y]",
      "[X] belongs to [Y]",
      "[X] is an element of [Y].",
      "[X] is a portion of [Y].",
      "[X] is a part of [Y]",
      "[X] is one of [Y].",
      "[X] belong to [Y].",
      "[X] is a component of [Y]",
      "[X] is [Y].",
      "[X] is part of the [Y]",
      "[X] is a part [Y].",
      "[X] is Part [Y].",
      "[X] is part [Y]",
    ],
  },
};
